### ISSUE TITLE
Change font and fix bugs

### ISSUE THREAD

**Issue by liljekvist** [NTIG-Uppsala/frisor-cleopatra#14]
Bugs in footer missing font. Robin wants us to change it also.

**Comment by Jonatan-Mone** [comment]
Fixed in 66e4040

**Comment by liljekvist** [comment]
Font is still not good. Reopening.

**Comment by liljekvist** [comment]
Fixed in commit 6f7d74cc19ffc2085eb2e503f2ec12569d73c532
